// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: workspace.proto

#include "workspace.pb.h"
#include "workspace.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace workspace {

static const char* Workspace_method_names[] = {
  "/workspace.Workspace/Create",
  "/workspace.Workspace/Read",
  "/workspace.Workspace/Update",
  "/workspace.Workspace/Delete",
};

std::unique_ptr< Workspace::Stub> Workspace::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Workspace::Stub> stub(new Workspace::Stub(channel, options));
  return stub;
}

Workspace::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Create_(Workspace_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Read_(Workspace_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Update_(Workspace_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Delete_(Workspace_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Workspace::Stub::Create(::grpc::ClientContext* context, const ::workspace::CreateRequest& request, ::workspace::CreateResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::workspace::CreateRequest, ::workspace::CreateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Create_, context, request, response);
}

void Workspace::Stub::async::Create(::grpc::ClientContext* context, const ::workspace::CreateRequest* request, ::workspace::CreateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::workspace::CreateRequest, ::workspace::CreateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Create_, context, request, response, std::move(f));
}

void Workspace::Stub::async::Create(::grpc::ClientContext* context, const ::workspace::CreateRequest* request, ::workspace::CreateResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Create_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::workspace::CreateResponse>* Workspace::Stub::PrepareAsyncCreateRaw(::grpc::ClientContext* context, const ::workspace::CreateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::workspace::CreateResponse, ::workspace::CreateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Create_, context, request);
}

::grpc::ClientAsyncResponseReader< ::workspace::CreateResponse>* Workspace::Stub::AsyncCreateRaw(::grpc::ClientContext* context, const ::workspace::CreateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Workspace::Stub::Read(::grpc::ClientContext* context, const ::workspace::ReadRequest& request, ::workspace::ReadResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::workspace::ReadRequest, ::workspace::ReadResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Read_, context, request, response);
}

void Workspace::Stub::async::Read(::grpc::ClientContext* context, const ::workspace::ReadRequest* request, ::workspace::ReadResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::workspace::ReadRequest, ::workspace::ReadResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Read_, context, request, response, std::move(f));
}

void Workspace::Stub::async::Read(::grpc::ClientContext* context, const ::workspace::ReadRequest* request, ::workspace::ReadResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Read_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::workspace::ReadResponse>* Workspace::Stub::PrepareAsyncReadRaw(::grpc::ClientContext* context, const ::workspace::ReadRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::workspace::ReadResponse, ::workspace::ReadRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Read_, context, request);
}

::grpc::ClientAsyncResponseReader< ::workspace::ReadResponse>* Workspace::Stub::AsyncReadRaw(::grpc::ClientContext* context, const ::workspace::ReadRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReadRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Workspace::Stub::Update(::grpc::ClientContext* context, const ::workspace::UpdateRequest& request, ::workspace::UpdateResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::workspace::UpdateRequest, ::workspace::UpdateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Update_, context, request, response);
}

void Workspace::Stub::async::Update(::grpc::ClientContext* context, const ::workspace::UpdateRequest* request, ::workspace::UpdateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::workspace::UpdateRequest, ::workspace::UpdateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Update_, context, request, response, std::move(f));
}

void Workspace::Stub::async::Update(::grpc::ClientContext* context, const ::workspace::UpdateRequest* request, ::workspace::UpdateResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Update_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::workspace::UpdateResponse>* Workspace::Stub::PrepareAsyncUpdateRaw(::grpc::ClientContext* context, const ::workspace::UpdateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::workspace::UpdateResponse, ::workspace::UpdateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Update_, context, request);
}

::grpc::ClientAsyncResponseReader< ::workspace::UpdateResponse>* Workspace::Stub::AsyncUpdateRaw(::grpc::ClientContext* context, const ::workspace::UpdateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Workspace::Stub::Delete(::grpc::ClientContext* context, const ::workspace::DeleteRequest& request, ::workspace::DeleteResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::workspace::DeleteRequest, ::workspace::DeleteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Delete_, context, request, response);
}

void Workspace::Stub::async::Delete(::grpc::ClientContext* context, const ::workspace::DeleteRequest* request, ::workspace::DeleteResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::workspace::DeleteRequest, ::workspace::DeleteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Delete_, context, request, response, std::move(f));
}

void Workspace::Stub::async::Delete(::grpc::ClientContext* context, const ::workspace::DeleteRequest* request, ::workspace::DeleteResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Delete_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::workspace::DeleteResponse>* Workspace::Stub::PrepareAsyncDeleteRaw(::grpc::ClientContext* context, const ::workspace::DeleteRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::workspace::DeleteResponse, ::workspace::DeleteRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Delete_, context, request);
}

::grpc::ClientAsyncResponseReader< ::workspace::DeleteResponse>* Workspace::Stub::AsyncDeleteRaw(::grpc::ClientContext* context, const ::workspace::DeleteRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteRaw(context, request, cq);
  result->StartCall();
  return result;
}

Workspace::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Workspace_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Workspace::Service, ::workspace::CreateRequest, ::workspace::CreateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Workspace::Service* service,
             ::grpc::ServerContext* ctx,
             const ::workspace::CreateRequest* req,
             ::workspace::CreateResponse* resp) {
               return service->Create(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Workspace_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Workspace::Service, ::workspace::ReadRequest, ::workspace::ReadResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Workspace::Service* service,
             ::grpc::ServerContext* ctx,
             const ::workspace::ReadRequest* req,
             ::workspace::ReadResponse* resp) {
               return service->Read(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Workspace_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Workspace::Service, ::workspace::UpdateRequest, ::workspace::UpdateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Workspace::Service* service,
             ::grpc::ServerContext* ctx,
             const ::workspace::UpdateRequest* req,
             ::workspace::UpdateResponse* resp) {
               return service->Update(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Workspace_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Workspace::Service, ::workspace::DeleteRequest, ::workspace::DeleteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Workspace::Service* service,
             ::grpc::ServerContext* ctx,
             const ::workspace::DeleteRequest* req,
             ::workspace::DeleteResponse* resp) {
               return service->Delete(ctx, req, resp);
             }, this)));
}

Workspace::Service::~Service() {
}

::grpc::Status Workspace::Service::Create(::grpc::ServerContext* context, const ::workspace::CreateRequest* request, ::workspace::CreateResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Workspace::Service::Read(::grpc::ServerContext* context, const ::workspace::ReadRequest* request, ::workspace::ReadResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Workspace::Service::Update(::grpc::ServerContext* context, const ::workspace::UpdateRequest* request, ::workspace::UpdateResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Workspace::Service::Delete(::grpc::ServerContext* context, const ::workspace::DeleteRequest* request, ::workspace::DeleteResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace workspace

